;===========================================================================;
;                                                                           ;
;       VERIFY COMPATIBILITY HANDLER FOR CHECK AGP INTERFACE PRESENT.       ;
;                                                                           ;
;===========================================================================;

Check_AGP:
clc
ret    ; AGP functionality reserved at UEFI version, see DOS debug version