;===========================================================================;
;                                                                           ;
;     VERIFY COMPATIBILITY HANDLER FOR CHECK FLAT FRAME BUFFER SUPPORT.     ;
;                                                                           ;
;===========================================================================;

Check_VFlt:
clc
ret    ; This functionality reserved