;===========================================================================;
;                                                                           ;
;                   CONSTANTS FOR CPU IDENTIFICATION.                       ;
;                                                                           ;
;===========================================================================;

Sign_CPU:
Sign_Intel   DB  'GenuineIntel'   ; Intel Vendor String
Sign_AMD     DB  'AuthenticAMD'   ; AMD Vendor String
