;===========================================================================;
;                                                                           ;
;                   SUBROUTINES FOR AGP OPERATIONS SUPPORT.                 ;
;                                                                           ;
;===========================================================================;

; AGP not supported at UEFI version, see DOS debug version