;===========================================================================;
;                                                                           ;
;                 RESTORE CONTEXT HANDLER FOR AGP SETTINGS.                 ;
;                                                                           ;
;===========================================================================;

Restore_AGP:
; Reserved at UEFI version, see DOS debug version.
clc
ret