;===========================================================================;
;                                                                           ;
;               SET CONTEXT HANDLER FOR ENABLE AGP FAST WRITE.              ;
;                                                                           ;
;===========================================================================;

Setup_AGP:
; This functionality disabled at UEFI version, see DOS debug version.
ret